### ISSUE TITLE
can't find the best.pt

### ISSUE THREAD

**Issue by MisakaMikoto-o** [minhquan24/Yolov8xNSFW#1]
can't find the best.pt yolov8 model file

**Comment by minhquan24** [comment]
Yeah, I ignored all the model while committing to Github. You can see in the gitignore file!

**Comment by MisakaMikoto-o** [comment]
> Yeah, I ignored all the model while committing to Github. You can see in the gitignore file!

Is there any way I can get it？

**Comment by minhquan24** [comment]
Yes! Can you create a shared google drive folder and leave me the link, I will upload the model there for you!

**Comment by MisakaMikoto-o** [comment]
https://drive.google.com/drive/folders/1JYnl3d-KrSIU-rxD16HncHofrmCnqZVX?usp=drive_link, thx!!!

> Yes! Can you create a shared google drive folder and leave me the link, I will upload the model there for you!
